name: flake8 Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install flake8 flake8-annotations
      - name: Check syntax
        run: flake8 --count --statistics --show-source
